import { Button, Flex } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Daily Anki</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Flex direction='column' align='center'>
          <Link href='/deck'>
            <Button as='a'>Memorize Deck</Button>
          </Link>
          <Link href='/chat'>
            <Button as='a'>Chat with AI</Button>
          </Link>
        </Flex>
      </main>
    </>
  )
}
